-- Valeurs initiales (toutes modifiables par l'admin)

INSERT INTO teams (id, name) VALUES (1, 'Équipe');

INSERT INTO maps (name, sort_order) VALUES ('Ancient',1),('Anubis',2),('Dust II',3),('Inferno',4),('Mirage',5),('Nuke',6),('Overpass',7),('Train',8);
INSERT INTO roles (side, name, sort_order) VALUES ('CT','Fixe A',1),('CT','Fixe B',2),('CT','Pivot A',3),('CT','Pivot B',4),('CT','AWP',5),('T','Extre A',1),('T','Extre B',2),('T','Central',3),('T','AWP',4),('T','+1',5);
INSERT INTO categories (name, shows_utility, shows_round_type, sort_order) VALUES ('Stuff',1,0,1),('Position',0,0,2),('Move solo',0,0,3),('Routine',0,0,4),('Prise de zone',0,0,5),('Reprise de zone',0,0,6),('Retake',0,0,7),('Post-plant',0,0,8),('Round lancé',0,1,9);
-- Dégradé vert → rouge : du moins au plus risqué.
INSERT INTO risks (name, color, sort_order) VALUES ('Passif','#22c55e',1),('En réaction','#a3e635',2),('Semi-agressif','#f97316',3),('Agressif','#ef4444',4);
INSERT INTO utilities (name, sort_order) VALUES ('Smoke',1),('Flash',2),('Molotov/Incendiaire',3),('HE',4),('Decoy',5);
INSERT INTO economies (name, sort_order) VALUES ('Pistol',1),('Eco',2),('Force buy',3),('Full buy',4);
INSERT INTO round_types (name, sort_order) VALUES ('Rush',1),('Déclic',2),('Strat',3),('Default',4),('Exé',5),('Fake',6),('Split',7),('Contact',8);
INSERT INTO principle_themes (name, sort_order) VALUES ('Fondamentaux',1),('Communication',2),('Utilitaire',3),('Économie',4),('Positionnement',5),('Duels & trades',6),('Post-plant & retake',7),('Mental',8);

-- Callouts courants par map (point de départ, à compléter par l'équipe).
INSERT INTO zones (map_id, name, sort_order) VALUES ((SELECT id FROM maps WHERE name='Mirage'),'T Spawn',1),((SELECT id FROM maps WHERE name='Mirage'),'T Ramp',2),((SELECT id FROM maps WHERE name='Mirage'),'Palace',3),((SELECT id FROM maps WHERE name='Mirage'),'Tetris',4),((SELECT id FROM maps WHERE name='Mirage'),'Sandwich',5),((SELECT id FROM maps WHERE name='Mirage'),'Firebox',6),((SELECT id FROM maps WHERE name='Mirage'),'Stairs',7),((SELECT id FROM maps WHERE name='Mirage'),'Jungle',8),((SELECT id FROM maps WHERE name='Mirage'),'Connector',9),((SELECT id FROM maps WHERE name='Mirage'),'CT Spawn',10),((SELECT id FROM maps WHERE name='Mirage'),'Ticket',11),((SELECT id FROM maps WHERE name='Mirage'),'Site A',12),((SELECT id FROM maps WHERE name='Mirage'),'Top Mid',13),((SELECT id FROM maps WHERE name='Mirage'),'Mid',14),((SELECT id FROM maps WHERE name='Mirage'),'Window',15),((SELECT id FROM maps WHERE name='Mirage'),'Short',16),((SELECT id FROM maps WHERE name='Mirage'),'Underpass',17),((SELECT id FROM maps WHERE name='Mirage'),'Apartments',18),((SELECT id FROM maps WHERE name='Mirage'),'Van',19),((SELECT id FROM maps WHERE name='Mirage'),'Bench',20),((SELECT id FROM maps WHERE name='Mirage'),'Market',21),((SELECT id FROM maps WHERE name='Mirage'),'Kitchen',22),((SELECT id FROM maps WHERE name='Mirage'),'Site B',23),((SELECT id FROM maps WHERE name='Mirage'),'Arch',24);
INSERT INTO zones (map_id, name, sort_order) VALUES ((SELECT id FROM maps WHERE name='Inferno'),'T Spawn',1),((SELECT id FROM maps WHERE name='Inferno'),'Banana',2),((SELECT id FROM maps WHERE name='Inferno'),'Car',3),((SELECT id FROM maps WHERE name='Inferno'),'Coffins',4),((SELECT id FROM maps WHERE name='Inferno'),'Construction',5),((SELECT id FROM maps WHERE name='Inferno'),'Site B',6),((SELECT id FROM maps WHERE name='Inferno'),'CT Spawn',7),((SELECT id FROM maps WHERE name='Inferno'),'Arch',8),((SELECT id FROM maps WHERE name='Inferno'),'Library',9),((SELECT id FROM maps WHERE name='Inferno'),'Pit',10),((SELECT id FROM maps WHERE name='Inferno'),'Graveyard',11),((SELECT id FROM maps WHERE name='Inferno'),'Site A',12),((SELECT id FROM maps WHERE name='Inferno'),'Apartments',13),((SELECT id FROM maps WHERE name='Inferno'),'Balcony',14),((SELECT id FROM maps WHERE name='Inferno'),'Boiler',15),((SELECT id FROM maps WHERE name='Inferno'),'Second Mid',16),((SELECT id FROM maps WHERE name='Inferno'),'Top Mid',17),((SELECT id FROM maps WHERE name='Inferno'),'Mid',18),((SELECT id FROM maps WHERE name='Inferno'),'Short',19),((SELECT id FROM maps WHERE name='Inferno'),'Long',20),((SELECT id FROM maps WHERE name='Inferno'),'Moto',21);
INSERT INTO zones (map_id, name, sort_order) VALUES ((SELECT id FROM maps WHERE name='Dust II'),'T Spawn',1),((SELECT id FROM maps WHERE name='Dust II'),'Long Doors',2),((SELECT id FROM maps WHERE name='Dust II'),'Long A',3),((SELECT id FROM maps WHERE name='Dust II'),'Pit',4),((SELECT id FROM maps WHERE name='Dust II'),'Car',5),((SELECT id FROM maps WHERE name='Dust II'),'Site A',6),((SELECT id FROM maps WHERE name='Dust II'),'Goose',7),((SELECT id FROM maps WHERE name='Dust II'),'Short',8),((SELECT id FROM maps WHERE name='Dust II'),'Catwalk',9),((SELECT id FROM maps WHERE name='Dust II'),'Mid',10),((SELECT id FROM maps WHERE name='Dust II'),'Xbox',11),((SELECT id FROM maps WHERE name='Dust II'),'Mid Doors',12),((SELECT id FROM maps WHERE name='Dust II'),'CT Spawn',13),((SELECT id FROM maps WHERE name='Dust II'),'Tunnels',14),((SELECT id FROM maps WHERE name='Dust II'),'Upper Tunnels',15),((SELECT id FROM maps WHERE name='Dust II'),'Lower Tunnels',16),((SELECT id FROM maps WHERE name='Dust II'),'Site B',17),((SELECT id FROM maps WHERE name='Dust II'),'Window',18),((SELECT id FROM maps WHERE name='Dust II'),'Back Plat',19);
INSERT INTO zones (map_id, name, sort_order) VALUES ((SELECT id FROM maps WHERE name='Nuke'),'T Spawn',1),((SELECT id FROM maps WHERE name='Nuke'),'Outside',2),((SELECT id FROM maps WHERE name='Nuke'),'Secret',3),((SELECT id FROM maps WHERE name='Nuke'),'Garage',4),((SELECT id FROM maps WHERE name='Nuke'),'Lobby',5),((SELECT id FROM maps WHERE name='Nuke'),'Squeaky',6),((SELECT id FROM maps WHERE name='Nuke'),'Hut',7),((SELECT id FROM maps WHERE name='Nuke'),'Heaven',8),((SELECT id FROM maps WHERE name='Nuke'),'Hell',9),((SELECT id FROM maps WHERE name='Nuke'),'Site A',10),((SELECT id FROM maps WHERE name='Nuke'),'Ramp',11),((SELECT id FROM maps WHERE name='Nuke'),'Site B',12),((SELECT id FROM maps WHERE name='Nuke'),'Vents',13),((SELECT id FROM maps WHERE name='Nuke'),'Control Room',14),((SELECT id FROM maps WHERE name='Nuke'),'Main',15),((SELECT id FROM maps WHERE name='Nuke'),'Mini',16),((SELECT id FROM maps WHERE name='Nuke'),'CT Spawn',17),((SELECT id FROM maps WHERE name='Nuke'),'Silo',18);
INSERT INTO zones (map_id, name, sort_order) VALUES ((SELECT id FROM maps WHERE name='Ancient'),'T Spawn',1),((SELECT id FROM maps WHERE name='Ancient'),'Main A',2),((SELECT id FROM maps WHERE name='Ancient'),'Donut',3),((SELECT id FROM maps WHERE name='Ancient'),'Temple',4),((SELECT id FROM maps WHERE name='Ancient'),'Site A',5),((SELECT id FROM maps WHERE name='Ancient'),'Mid',6),((SELECT id FROM maps WHERE name='Ancient'),'Cave',7),((SELECT id FROM maps WHERE name='Ancient'),'Ramp',8),((SELECT id FROM maps WHERE name='Ancient'),'Site B',9),((SELECT id FROM maps WHERE name='Ancient'),'CT Spawn',10),((SELECT id FROM maps WHERE name='Ancient'),'Elbow',11),((SELECT id FROM maps WHERE name='Ancient'),'Red Room',12),((SELECT id FROM maps WHERE name='Ancient'),'Pillar',13),((SELECT id FROM maps WHERE name='Ancient'),'Lane',14);
INSERT INTO zones (map_id, name, sort_order) VALUES ((SELECT id FROM maps WHERE name='Anubis'),'T Spawn',1),((SELECT id FROM maps WHERE name='Anubis'),'Main A',2),((SELECT id FROM maps WHERE name='Anubis'),'Canal',3),((SELECT id FROM maps WHERE name='Anubis'),'Connector',4),((SELECT id FROM maps WHERE name='Anubis'),'Mid',5),((SELECT id FROM maps WHERE name='Anubis'),'Bridge',6),((SELECT id FROM maps WHERE name='Anubis'),'Site A',7),((SELECT id FROM maps WHERE name='Anubis'),'Heaven',8),((SELECT id FROM maps WHERE name='Anubis'),'Main B',9),((SELECT id FROM maps WHERE name='Anubis'),'Site B',10),((SELECT id FROM maps WHERE name='Anubis'),'Ruins',11),((SELECT id FROM maps WHERE name='Anubis'),'Street',12),((SELECT id FROM maps WHERE name='Anubis'),'Palace',13),((SELECT id FROM maps WHERE name='Anubis'),'CT Spawn',14),((SELECT id FROM maps WHERE name='Anubis'),'Water',15);
INSERT INTO zones (map_id, name, sort_order) VALUES ((SELECT id FROM maps WHERE name='Overpass'),'T Spawn',1),((SELECT id FROM maps WHERE name='Overpass'),'Fountain',2),((SELECT id FROM maps WHERE name='Overpass'),'Toilets',3),((SELECT id FROM maps WHERE name='Overpass'),'Long A',4),((SELECT id FROM maps WHERE name='Overpass'),'Site A',5),((SELECT id FROM maps WHERE name='Overpass'),'Truck',6),((SELECT id FROM maps WHERE name='Overpass'),'Bank',7),((SELECT id FROM maps WHERE name='Overpass'),'Connector',8),((SELECT id FROM maps WHERE name='Overpass'),'Party',9),((SELECT id FROM maps WHERE name='Overpass'),'Monster',10),((SELECT id FROM maps WHERE name='Overpass'),'Water',11),((SELECT id FROM maps WHERE name='Overpass'),'Short B',12),((SELECT id FROM maps WHERE name='Overpass'),'Heaven',13),((SELECT id FROM maps WHERE name='Overpass'),'Pillar',14),((SELECT id FROM maps WHERE name='Overpass'),'Site B',15),((SELECT id FROM maps WHERE name='Overpass'),'Barrels',16),((SELECT id FROM maps WHERE name='Overpass'),'CT Spawn',17);
INSERT INTO zones (map_id, name, sort_order) VALUES ((SELECT id FROM maps WHERE name='Train'),'T Spawn',1),((SELECT id FROM maps WHERE name='Train'),'Main',2),((SELECT id FROM maps WHERE name='Train'),'Ivy',3),((SELECT id FROM maps WHERE name='Train'),'Connector',4),((SELECT id FROM maps WHERE name='Train'),'Site A',5),((SELECT id FROM maps WHERE name='Train'),'Ladder',6),((SELECT id FROM maps WHERE name='Train'),'Popdog',7),((SELECT id FROM maps WHERE name='Train'),'Site B',8),((SELECT id FROM maps WHERE name='Train'),'Upper B',9),((SELECT id FROM maps WHERE name='Train'),'Lower B',10),((SELECT id FROM maps WHERE name='Train'),'Hell',11),((SELECT id FROM maps WHERE name='Train'),'Heaven',12),((SELECT id FROM maps WHERE name='Train'),'CT Spawn',13),((SELECT id FROM maps WHERE name='Train'),'Z Connector',14);
