// Scénario de bout en bout : login, formulaire, filtres, détail, admin, import, mobile.
// Lancé par e2e/run.mjs (base neuve à chaque exécution, connexion de test activée).
import { mkdirSync } from 'node:fs'
import { chromium } from 'playwright'

const BASE = process.env.BASE_URL ?? 'http://localhost:5173'
const SHOTS = process.env.SHOTS ?? 'e2e/screenshots'
mkdirSync(SHOTS, { recursive: true })
const users = {
  admin: { email: 'admin@team.gg' },
  member: { email: 'membre@team.gg' },
}
const browser = await chromium.launch(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {})
const errors = []
async function ctxFor(user, viewport = { width: 1440, height: 900 }) {
  const ctx = await browser.newContext({ viewport })
  // Connexion par l'API de test : le cookie de session est partagé avec la page.
  if (user) {
    const r = await ctx.request.post(BASE + '/api/auth/dev', { data: { email: user.email }, headers: { 'x-requested-with': 'cs2kb' } })
    if (!r.ok()) throw new Error('connexion de test impossible : ' + (await r.text()))
  }
  const page = await ctx.newPage()
  current = page
  page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`))
  page.on('console', (m) => m.type() === 'error' && !/youtube|noembed|ytimg|imgur|Failed to load resource/.test(m.text()) && errors.push(`console: ${m.text()}`))
  return page
}
const shot = (page, name) => page.screenshot({ path: `${SHOTS}/${name}.png`, fullPage: false })
/** Ouvre un lien d'inscription et remplit le formulaire (pseudo prérempli par l'invitation). */
async function signup(page, url, { email, password, shotName }) {
  await page.goto(url)
  await page.getByText('Crée ton compte').waitFor()
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Mot de passe', { exact: true }).fill(password)
  await page.getByLabel('Confirme le mot de passe').fill(password)
  if (shotName) await shot(page, shotName)
  await page.getByRole('button', { name: 'Créer mon compte' }).click()
}
const step = (s) => console.log('✓', s)
let current
process.on('uncaughtException', async (e) => { console.log('FAIL', e.message.split('\n')[0]); try { await current?.screenshot({ path: `${SHOTS}/fail.png`, fullPage: true }) } catch {} ; console.log(errors.join('\n')); process.exit(1) })

// 1. anonyme
let page = await ctxFor(null)
await page.goto(BASE + '/c/1')
await page.getByText("lien d'inscription").waitFor()
await page.getByLabel('Mot de passe').waitFor()
if (await page.getByText('Discord').count()) throw new Error('Discord encore affiché sur la page de connexion')
await shot(page, '01-login'); step('login affiché sans session')

// 2. intrus (connexion de test avec un email inconnu)
await page.getByLabel('Email (développement)').fill('intrus@x.gg')
await page.getByRole('button', { name: 'Connexion de test' }).click()
await page.getByText("n'est pas sur la liste des membres").waitFor(); step('intrus refusé')

// 3. admin : formulaire (un stuff, puis une stratégie qui l'utilise)
page = await ctxFor(users.admin)
await page.goto(BASE)
await page.getByText('La base est vide').waitFor(); step('admin connecté, base vide')
await page.keyboard.press('n')
await page.getByRole('heading', { name: 'Nouvelle stratégie' }).waitFor(); step('touche N ouvre le formulaire (stratégie)')
// validation
await page.getByRole('button', { name: 'Publier' }).click()
await page.getByText('Choisis une map.').waitFor()
await page.getByText('Le titre est obligatoire.').waitFor()
await page.getByText('Coche au moins une catégorie.').waitFor(); step('erreurs de validation en ligne')
if (await page.getByText("Type d'utilitaire").count()) throw new Error('utilitaire visible sur une stratégie')
await page.getByRole('radio', { name: /Stuff/ }).click()
await page.getByRole('heading', { name: 'Nouveau stuff' }).waitFor()
await page.getByText("Choisis le type d'utilitaire (smoke, flash…).").waitFor(); step('stuff : utilitaire obligatoire, pas de catégorie exigée')
const link = page.getByLabel('Lien média')
await link.fill('https://youtu.be/dQw4w9WgXcQ?t=75')
await link.press('Enter')
await page.locator('input[placeholder="mm:ss"]').waitFor()
const start = await page.locator('input[placeholder="mm:ss"]').inputValue()
if (start !== '1:15') throw new Error('timestamp attendu 1:15, reçu ' + start)
await page.locator('input[placeholder="mm:ss"]').fill('0:42'); step('lien YouTube détecté, début modifiable')
await page.getByLabel('Source', { exact: true }).selectOption({ label: '+ Ajouter une source…' })
await page.getByLabel('Nouvelle source').fill('Coach Max')
await page.getByLabel('Nouvelle source').press('Enter')
await page.getByText('Source « Coach Max » ajoutée').waitFor()
if ((await page.getByLabel('Source', { exact: true }).locator('option:checked').textContent()) !== 'Coach Max') throw new Error('source non sélectionnée')
step('source ajoutée depuis la liste déroulante')
await page.getByRole('button', { name: 'Mirage', exact: true }).click()
await page.getByRole('button', { name: 'CT', exact: true }).click()
await page.getByRole('button', { name: 'Smoke', exact: true }).click()
await page.getByRole('button', { name: 'Pivot B', exact: true }).click()
await page.getByLabel('Chercher une zone').fill('Palace')
await page.getByLabel('Chercher une zone').press('Enter')
await page.getByLabel('Chercher une zone').fill('Chaise rouge')
await page.getByRole('button', { name: /Nouvelle zone « Chaise rouge »/ }).click()
await page.getByText(/créée \(à valider/).waitFor(); step('zone proposée depuis le formulaire')
await page.getByRole('button', { name: 'Passif', exact: true }).click()
await page.getByRole('button', { name: 'Full buy', exact: true }).click()
await page.locator('#title').fill('Smoke Palace depuis CT')
await page.locator('#description').fill('**Jumpthrow** en visant l’antenne.\n- rapide\n- sûr')
await page.waitForTimeout(3000)
await page.getByText(/Brouillon enregistré à/).waitFor(); step('autosave serveur en brouillon')
await shot(page, '02-form-stuff')
await page.getByRole('button', { name: /Enregistrer et en créer une autre/ }).click()
await page.getByText('Carte publiée').waitFor()
await page.waitForTimeout(300)
const kept = await page.getByRole('button', { name: 'Mirage', exact: true }).getAttribute('aria-pressed')
const title2 = await page.locator('#title').inputValue()
if (kept !== 'true' || title2 !== '') throw new Error('série : valeurs non conservées')
await page.getByRole('heading', { name: 'Nouveau stuff' }).waitFor()
step('série : type, map, side conservés, reste vidé')
// La carte suivante est une stratégie : action de chaque rôle + stuff rattaché.
await page.getByRole('radio', { name: /Stratégie/ }).click()
await page.getByText('Que fait chaque rôle ?').waitFor()
await page.getByRole('radio', { name: 'Pivot B : Support' }).click()
await page.getByLabel('Précision pour Pivot B').fill('lance la smoke Palace')
await page.getByRole('radio', { name: 'Fixe A : Non concerné' }).click()
await page.getByRole('button', { name: 'Position', exact: true }).click()
await page.getByRole('button', { name: 'Ajouter Smoke Palace depuis CT' }).click()
await page.getByLabel('Qui lance Smoke Palace depuis CT').selectOption({ label: 'Pivot B' })
await page.locator('#title').fill('Position fenêtre Palace')
await page.locator('#description').fill('Tenir depuis le coin')
await shot(page, '02-form-strategy')
await page.getByRole('button', { name: 'Publier' }).click()
await page.waitForURL(/\/(\?.*)?$/)
step('stratégie : actions des rôles + stuff rattaché → retour liste : ' + page.url())

// 4. rubriques séparées et filtres
await page.goto(BASE + '/stuff')
await page.getByRole('heading', { name: 'Playbook' }).waitFor()
await page.getByRole('link', { name: '💨 Stuff' }).waitFor()
await page.getByText('1 stuff', { exact: true }).waitFor()
if (await page.getByText('Position fenêtre Palace').count()) throw new Error('stratégie affichée dans le stuff')
await page.getByRole('button', { name: /^Mirage\s*1$/ }).click()
await page.getByRole('button', { name: /^CT\s*1$/ }).first().click()
await page.getByRole('button', { name: /^Smoke\s*1$/ }).click()
await page.getByText('1 stuff', { exact: true }).waitFor()
if (!/map=\d+&side=CT&util=\d+/.test(page.url())) throw new Error('URL filtres : ' + page.url())
step('stuff : filtres ET/OU + compteurs + URL : ' + page.url())
await shot(page, '03-browse-stuff')
await page.goto(BASE)
await page.getByText('1 stratégie', { exact: true }).waitFor()
if (await page.getByText('Smoke Palace depuis CT').count()) throw new Error('stuff affiché dans les stratégies')
await page.getByRole('button', { name: /^Support\s*1$/ }).click()
await page.getByText('1 stratégie', { exact: true }).waitFor()
if (!/act=\d+/.test(page.url())) throw new Error('filtre action absent de l’URL')
step('stratégies séparées du stuff ; filtre par action de rôle')
await shot(page, '03-browse')
await page.getByRole('button', { name: 'Réinitialiser les filtres' }).click()
await page.getByLabel('Recherche').fill('fenetre')
await page.getByText('1 stratégie', { exact: true }).waitFor(); step('recherche sans accents')
await page.getByLabel('Recherche').fill('')

// 5. détail : rôles, stuffs utilisés, et le stuff renvoie vers la stratégie
await page.getByRole('link', { name: /Position fenêtre Palace/ }).click()
await page.getByRole('dialog').waitFor()
await page.getByRole('dialog').getByText('Rôle de chacun').waitFor()
await page.getByRole('dialog').getByText('lance la smoke Palace').waitFor()
await page.getByRole('dialog').getByText('Stuffs utilisés (1)').waitFor()
await shot(page, '04-detail-strategy')
await page.getByRole('dialog').getByRole('link', { name: /Smoke Palace depuis CT/ }).click()
await page.getByRole('dialog').getByText('Chaise rouge').first().waitFor()
await page.getByRole('dialog').getByText('Utilisé dans 1 stratégie').waitFor()
await page.getByRole('dialog').getByText('📺 Coach Max').waitFor()
if (!/\/c\/\d+$/.test(page.url())) throw new Error('URL détail')
await page.getByRole('button', { name: /Historique/ }).click()
await page.getByText('Carte créée').waitFor(); step('vue détaillée : stuffs cliquables, « utilisé dans », historique')
await shot(page, '04-detail')
const cardUrl = page.url()

// 6. membre : signale « à revoir », ne peut pas modifier ; ses rôles en jeu
page = await ctxFor(users.member)
await page.goto(cardUrl)
await page.getByRole('heading', { name: 'Smoke Palace depuis CT' }).waitFor()
if (await page.getByRole('link', { name: /Modifier/ }).count()) throw new Error('membre peut modifier la carte d’autrui')
await page.getByRole('button', { name: /Signaler/ }).click()
await page.getByPlaceholder(/la smoke ne passe plus/).fill('Ne passe plus depuis la MAJ')
await page.getByRole('button', { name: 'Signaler', exact: true }).click()
await page.getByText('Ne passe plus depuis la MAJ').waitFor(); step('URL partageable + membre signale « À revoir »')
await page.getByRole('button', { name: /Dupliquer/ }).click()
await page.locator('#title').waitFor()
if ((await page.locator('#title').inputValue()) !== 'Smoke Palace depuis CT (copie)') throw new Error('dupliquer')
await page.getByRole('heading', { name: 'Nouveau stuff' }).waitFor()
step('dupliquer pré-remplit le formulaire (type conservé)')
await page.goto(BASE + '/stuff?view=review')
await page.getByText('1 stuff', { exact: true }).waitFor(); step('filtre « À revoir »')
await page.goto(BASE + '/moi')
await page.getByRole('heading', { name: 'Mes rôles en jeu' }).waitFor()
await page.getByRole('button', { name: 'Pivot B', exact: true }).click()
await page.getByRole('link', { name: /Position fenêtre Palace/ }).waitFor()
await shot(page, '24-me')
step('mon espace : rôles en jeu → stratégies que je joue')
await page.goto(BASE + '/?mesroles=1')
await page.getByText('1 stratégie', { exact: true }).waitFor()
await page.getByText('Toi (Pivot B) :').waitFor()
await page.getByRole('link', { name: /Position fenêtre Palace/ }).click()
await page.getByRole('dialog').getByText('Ton rôle : Pivot B').waitFor(); step('« Mes rôles » + « Ton rôle » mis en avant')
await shot(page, '25-my-role')
await page.keyboard.press('Escape')

// 7. admin : zones à valider, fusion
page = await ctxFor(users.admin)
await page.goto(BASE + '/admin/zones')
await page.getByText('Zones proposées à valider (1)').waitFor()
await shot(page, '05-admin-zones')
page.once('dialog', (d) => d.accept())
await page.getByLabel('Fusionner avec').selectOption({ label: 'Palace' })
await page.getByText('Zones fusionnées').waitFor(); step('fusion de zone (admin)')
await page.goto(BASE + '/admin/actions')
await page.getByRole('heading', { name: 'Actions des rôles' }).waitFor()
await page.getByText('Non concerné').first().waitFor(); step('admin : liste des actions des rôles')

// 8. import CSV
await page.goto(BASE + '/import')
await page.getByPlaceholder(/colle le contenu CSV/).fill('titre;liens;map;side;roles;categories;zones\nImport 1;https://imgur.com/AbC123x;mirage;ct;fixe a;position;Jungle\nImport 2;;Nuke;X;;Inconnue;')
await page.getByText('1 valide(s)').waitFor()
await page.getByText(/Side invalide/).waitFor()
await shot(page, '06-import')
await page.getByRole('button', { name: 'Importer 1 carte' }).click()
await page.getByText('1 carte importée.').waitFor(); step('import CSV avec prévisualisation')

// 9. mobile
page = await ctxFor(users.member, { width: 390, height: 844 })
await page.goto(BASE)
await page.getByLabel('Ajouter : stratégie').waitFor()
await page.getByRole('navigation', { name: 'Navigation principale' }).getByRole('link', { name: /Playbook/ }).waitFor()
await page.getByRole('link', { name: '💨 Stuff' }).click()
await page.getByLabel('Ajouter : stuff').waitFor()
await page.goto(BASE)
await shot(page, '07-mobile')
await page.getByRole('button', { name: /^Filtres/ }).click()
await shot(page, '08-mobile-filters')
await page.goto(BASE + '/new?map=5&side=CT')
await page.getByText('Pré-rempli avec les filtres actifs.').waitFor()
await shot(page, '09-mobile-form')
// sauvegarde locale : rechargement sans perte
await page.locator('#title').fill('Ne pas perdre ce titre')
await page.waitForTimeout(600)
await page.reload()
await page.getByText('Saisie non terminée restaurée.').waitFor()
if ((await page.locator('#title').inputValue()) !== 'Ne pas perdre ce titre') throw new Error('restauration')
step('saisie restaurée après rechargement')
await page.getByRole('button', { name: 'Repartir de zéro' }).click()
if ((await page.locator('#title').inputValue()) !== '') throw new Error('repartir de zéro')
// modification de sa propre carte (la carte importée n'est pas à lui, la copie non plus) : on édite en admin
page = await ctxFor(users.admin)
await page.goto(BASE + '/c/2/edit')
await page.locator('#title').fill('Position fenêtre Palace (maj)')
await page.getByRole('button', { name: 'Enregistrer' }).click()
await page.getByRole('heading', { name: 'Position fenêtre Palace (maj)' }).waitFor()
await page.getByRole('button', { name: /Historique/ }).click()
await page.getByText(/Titre : « Position fenêtre Palace » → « Position fenêtre Palace \(maj\) »/).waitFor()
await shot(page, '10-edit-history'); step('mobile : FAB, filtres repliables, formulaire')

// 10. cartes de démo + tableau de bord
page = await ctxFor(users.admin)
await page.goto(BASE + '/admin/demo')
await page.getByRole('button', { name: 'Charger les cartes de démo' }).click()
await page.getByText('13 cartes et 4 principes de démo créés').waitFor({ timeout: 60000 })
step('13 cartes + 4 principes de démo créés')
await page.goto(BASE + '/?view=drafts')
await page.getByText('[Démo] Brouillon de test').waitFor()
await page.goto(BASE + '/stuff?view=review')
await page.getByText('[Démo] Flash pop Mid').waitFor(); step('démo : brouillon privé et stuff « À revoir »')
await page.goto(BASE + '/')
await shot(page, '11-demo-grid')
await page.getByRole('link', { name: /Exé B complète/ }).click()
// Lien externe affiché (une image qui ne charge pas affiche aussi « Ouvrir ↗ » : on prend le premier).
await page.getByRole('dialog').getByText('Ouvrir ↗').first().waitFor()
await page.getByRole('dialog').getByText('reste Apps pour couper la rotation').waitFor()
const before = page.url()
await page.keyboard.press('ArrowRight')
await page.waitForURL((u) => u.toString() !== before)
await page.getByRole('button', { name: /Carte précédente/ }).click()
await page.waitForURL(before); step('détail : navigation précédente / suivante')
await shot(page, '12-demo-detail')
await page.keyboard.press('Escape')
// rounds lancés : filtre, badge, formulaire conditionnel
await page.goto(BASE + '/')
await page.getByRole('button', { name: /^Rush\s*1$/ }).click()
await page.getByText('1 stratégie', { exact: true }).waitFor()
if (!/round=\d+/.test(page.url())) throw new Error('filtre round absent de l’URL')
await page.getByText('⚡ Rush').first().waitFor(); step('filtre « Round lancé » + badge')
await page.goto(BASE + '/new')
if (await page.getByText('Type de round').count()) throw new Error('type de round visible sans la catégorie')
await page.getByRole('button', { name: 'Round lancé', exact: true }).click()
await page.getByText(/\d+\. Type de round/).waitFor()
await page.getByRole('button', { name: 'Déclic', exact: true }).waitFor(); step('formulaire : type de round si « Round lancé »')

// principes de jeu
await page.goto(BASE + '/principes')
await page.getByText('[Démo] Toujours jouer en trade').waitFor()
await shot(page, '15-principles')
await page.getByText('[Démo] Toujours jouer en trade').click()
await page.getByRole('heading', { name: 'Cartes rattachées (2)' }).waitFor(); step('principes : liste par thème + cartes rattachées')
await shot(page, '16-principle-detail')
await page.getByRole('link', { name: /Rush B fumé/ }).first().click()
await page.getByRole('dialog').getByText('[Démo] Un rush se déclenche sur une info, pas sur un timer').waitFor()
await page.getByRole('dialog').getByText('via étiquettes').first().waitFor(); step('carte : principes rattachés + via étiquettes')
await page.getByRole('dialog').getByText('Stuffs utilisés (1)').waitFor()
await page.getByRole('dialog').getByText('[Démo] Smoke Window depuis T Spawn').waitFor(); step('démo : stuff rattaché à « Rush B fumé »')
await shot(page, '17-card-principles')
await page.keyboard.press('Escape')
await page.goto(BASE + '/principes/new')
await page.locator('#ptitle').fill('Jouer les post-plants en crossfire')
await page.getByRole('button', { name: 'T', exact: true }).click()
await page.getByRole('button', { name: 'Post-plant', exact: true }).click()
await page.getByText(/→ 1 carte concernée/).waitFor()
await page.getByRole('button', { name: 'Créer le principe' }).click()
await page.getByRole('heading', { name: /Concernées par les étiquettes \(1\)/ }).waitFor(); step('création d’un principe par étiquettes')

await page.goto(BASE + '/stats')
await page.getByText('Couverture map × rôle').waitFor()
await page.getByText('Cartes dans la base').waitFor()
await shot(page, '13-dashboard')
await page.getByRole('radio', { name: 'T', exact: true }).click()
await page.locator('th', { hasText: 'Extre A' }).waitFor()
await page.getByRole('radio', { name: '12 mois' }).click()
await page.screenshot({ path: `${SHOTS}/14-dashboard-full.png`, fullPage: true })
step('tableau de bord : KPI, activité, couverture CT/T, périodes')
page.once('dialog', (d) => d.accept())
await page.goto(BASE + '/admin/demo')
await page.getByRole('button', { name: /Supprimer les données de démo/ }).click()
await page.getByText('Données de démo supprimées').waitFor(); step('suppression des données de démo')

// 11. équipes : l'admin crée une équipe, le capitaine invite une recrue
page = await ctxFor(users.admin)
await page.goto(BASE + '/equipes')
await page.getByLabel("Nom de l'équipe").fill('Alpha')
await page.getByLabel('Capitaine').selectOption({ label: 'Capitaine : Apex' })
await page.getByRole('button', { name: 'Créer' }).click()
await page.getByRole('heading', { name: 'Alpha' }).waitFor(); step('admin crée une équipe avec son capitaine')
page = await ctxFor(users.member)
await page.goto(BASE + '/equipes')
await page.getByText('Capitaine', { exact: true }).first().waitFor()
await page.getByLabel('Pseudo du joueur invité').fill('Recrue')
await page.getByRole('button', { name: 'Inviter' }).click()
const recrueLink = await page.getByLabel("Lien d'inscription").inputValue()
await page.keyboard.press('Escape')
await page.getByText('Invitations en attente').waitFor()
await shot(page, '18-teams')
const recrue = await ctxFor(null)
await signup(recrue, recrueLink, { email: 'recrue@team.gg', password: 'recrue-mdp-123' })
await recrue.getByRole('link', { name: 'Playbook', exact: true }).waitFor(); step('capitaine invite une recrue, qui s’inscrit par son lien et rejoint l’équipe')

// 12 bis. Playbook : le capitaine met une stratégie « à apprendre », la recrue note son niveau
await page.goto(BASE + '/')
await page.getByRole('link', { name: /Position fenêtre Palace/ }).click()
await page.getByRole('dialog').getByRole('radio', { name: 'À apprendre' }).click()
await page.getByText(/: à apprendre$/).waitFor(); step('capitaine : stratégie « à apprendre » pour l’équipe')
await page.keyboard.press('Escape')
await recrue.goto(BASE + '/?aapprendre=1')
await recrue.getByText('1 stratégie', { exact: true }).waitFor()
await recrue.getByText('📌 À apprendre').first().waitFor()
await recrue.getByRole('radiogroup', { name: /Mon niveau sur Position fenêtre Palace/ }).getByRole('radio', { name: /^4 sur 5/ }).click()
await recrue.getByText('Solide').first().waitFor(); step('joueur : filtre « À apprendre » et note sur 5 depuis la vignette')
await shot(recrue, '26-to-learn')
await recrue.goto(BASE + '/moi')
await recrue.getByRole('heading', { name: 'À apprendre' }).waitFor()
await recrue.getByText('1/1 maîtrisée par toi').waitFor(); step('mon espace : stratégies à apprendre et progression')
await page.goto(BASE + '/equipes')
await page.getByText("Playbook de l'équipe").first().waitFor()
await page.getByRole('cell', { name: '4.0' }).waitFor(); step('capitaine : tableau des notes de l’équipe')
await shot(page, '27-team-learning')
await shot(recrue, '21-skills-player')

// 13. lien d'inscription (admin) puis connexion email + mot de passe
page = await ctxFor(users.admin)
await page.goto(BASE + '/admin/membres')
await page.getByLabel('Pseudo').fill('Coach')
await page.getByRole('button', { name: 'Inviter' }).click()
const invite = await page.getByLabel("Lien d'inscription").inputValue()
await shot(page, '22-invite-link')
page = await ctxFor(null)
await signup(page, invite, { email: 'coach@team.gg', password: 'coach-mdp-123', shotName: '23-signup' })
await page.getByRole('link', { name: 'Playbook', exact: true }).waitFor(); step("lien d'inscription : compte créé (email + mot de passe)")
// Le lien ne sert qu'une fois.
await page.goto(invite)
await page.getByText('a déjà été utilisé').waitFor(); step("lien d'inscription : refusé à la 2e utilisation")
// Déconnexion puis connexion avec l'email et le mot de passe choisis.
await page.request.post(BASE + '/api/auth/logout', { headers: { 'x-requested-with': 'cs2kb' } })
await page.goto(BASE)
await page.getByLabel('Email', { exact: true }).fill('coach@team.gg')
await page.getByLabel('Mot de passe').fill('mauvais-mdp')
await page.getByRole('button', { name: 'Se connecter' }).click()
await page.getByText('Email ou mot de passe incorrect.').waitFor()
await page.getByLabel('Mot de passe').fill('coach-mdp-123')
await page.getByRole('button', { name: 'Se connecter' }).click()
await page.getByRole('link', { name: 'Playbook', exact: true }).waitFor(); step('connexion par email + mot de passe')

await browser.close()
if (errors.length) { console.log('ERREURS NAVIGATEUR:\n' + errors.join('\n')); process.exit(1) }
console.log('E2E OK')
