// Scénario de bout en bout : login, formulaire, filtres, détail, admin, import, mobile.
// Lancé par e2e/run.mjs (base neuve à chaque exécution, connexion de test activée).
import { mkdirSync } from 'node:fs'
import { chromium } from 'playwright'

const BASE = process.env.BASE_URL ?? 'http://localhost:5173'
const SHOTS = process.env.SHOTS ?? 'e2e/screenshots'
mkdirSync(SHOTS, { recursive: true })
const users = {
  admin: { email: 'admin@team.gg' },
  member: { email: 'membre@team.gg' },
}
const browser = await chromium.launch(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {})
const errors = []
async function ctxFor(user, viewport = { width: 1440, height: 900 }) {
  const ctx = await browser.newContext({ viewport })
  // Connexion par l'API de test : le cookie de session est partagé avec la page.
  if (user) {
    const r = await ctx.request.post(BASE + '/api/auth/dev', { data: { email: user.email }, headers: { 'x-requested-with': 'cs2kb' } })
    if (!r.ok()) throw new Error('connexion de test impossible : ' + (await r.text()))
  }
  const page = await ctx.newPage()
  current = page
  page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`))
  page.on('console', (m) => m.type() === 'error' && !/youtube|noembed|ytimg|imgur|Failed to load resource/.test(m.text()) && errors.push(`console: ${m.text()}`))
  return page
}
const shot = (page, name) => page.screenshot({ path: `${SHOTS}/${name}.png`, fullPage: false })
/** Ouvre un lien d'inscription et remplit le formulaire (pseudo prérempli par l'invitation). */
async function signup(page, url, { email, password, shotName }) {
  await page.goto(url)
  await page.getByText('Crée ton compte').waitFor()
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Mot de passe', { exact: true }).fill(password)
  await page.getByLabel('Confirme le mot de passe').fill(password)
  if (shotName) await shot(page, shotName)
  await page.getByRole('button', { name: 'Créer mon compte' }).click()
}
const step = (s) => console.log('✓', s)
let current
process.on('uncaughtException', async (e) => { console.log('FAIL', e.message.split('\n')[0]); try { await current?.screenshot({ path: `${SHOTS}/fail.png`, fullPage: true }) } catch {} ; console.log(errors.join('\n')); process.exit(1) })

// 1. anonyme
let page = await ctxFor(null)
await page.goto(BASE + '/c/1')
await page.getByText("lien d'inscription").waitFor()
await page.getByLabel('Mot de passe').waitFor()
if (await page.getByText('Discord').count()) throw new Error('Discord encore affiché sur la page de connexion')
await shot(page, '01-login'); step('login affiché sans session')

// 2. intrus (connexion de test avec un email inconnu)
await page.getByLabel('Email (développement)').fill('intrus@x.gg')
await page.getByRole('button', { name: 'Connexion de test' }).click()
await page.getByText("n'est pas sur la liste des membres").waitFor(); step('intrus refusé')

// 3. admin : formulaire
page = await ctxFor(users.admin)
await page.goto(BASE)
await page.getByText('La base est vide').waitFor(); step('admin connecté, base vide')
await page.keyboard.press('n')
await page.getByText('Nouvelle carte').waitFor(); step('touche N ouvre le formulaire')
// validation
await page.getByRole('button', { name: 'Publier' }).click()
await page.getByText('Choisis une map.').waitFor()
await page.getByText('Le titre est obligatoire.').waitFor(); step('erreurs de validation en ligne')
const link = page.getByLabel('Lien média')
await link.fill('https://youtu.be/dQw4w9WgXcQ?t=75')
await link.press('Enter')
await page.locator('input[placeholder="mm:ss"]').waitFor()
const start = await page.locator('input[placeholder="mm:ss"]').inputValue()
if (start !== '1:15') throw new Error('timestamp attendu 1:15, reçu ' + start)
await page.locator('input[placeholder="mm:ss"]').fill('0:42'); step('lien YouTube détecté, début modifiable')
await page.getByRole('button', { name: 'Mirage', exact: true }).click()
await page.getByRole('button', { name: 'CT', exact: true }).click()
await page.getByRole('button', { name: 'Pivot B', exact: true }).click()
await page.getByLabel('Chercher une zone').fill('Palace')
await page.getByLabel('Chercher une zone').press('Enter')
await page.getByLabel('Chercher une zone').fill('Chaise rouge')
await page.getByRole('button', { name: /Nouvelle zone « Chaise rouge »/ }).click()
await page.getByText(/créée \(à valider/).waitFor(); step('zone proposée depuis le formulaire')
if (await page.getByText("7. Type d'utilitaire").count()) throw new Error('utilitaire visible sans Stuff')
await page.getByRole('button', { name: 'Stuff', exact: true }).click()
await page.getByText("7. Type d'utilitaire").waitFor(); step('utilitaire apparaît avec Stuff')
await page.getByRole('button', { name: 'Smoke', exact: true }).click()
await page.getByRole('button', { name: 'Passif', exact: true }).click()
await page.getByRole('button', { name: 'Full buy', exact: true }).click()
await page.locator('#title').fill('Smoke Palace depuis CT')
await page.locator('#description').fill('**Jumpthrow** en visant l’antenne.\n- rapide\n- sûr')
await page.waitForTimeout(3000)
await page.getByText(/Brouillon enregistré à/).waitFor(); step('autosave serveur en brouillon')
await shot(page, '02-form')
await page.getByRole('button', { name: /Enregistrer et en créer une autre/ }).click()
await page.getByText('Carte publiée').waitFor()
await page.waitForTimeout(300)
const kept = await page.getByRole('button', { name: 'Mirage', exact: true }).getAttribute('aria-pressed')
const keptRole = await page.getByRole('button', { name: 'Pivot B', exact: true }).getAttribute('aria-pressed')
const title2 = await page.locator('#title').inputValue()
if (kept !== 'true' || keptRole !== 'true' || title2 !== '') throw new Error('série : valeurs non conservées')
step('série : map/side/rôle conservés, reste vidé')
await page.getByRole('button', { name: 'Position', exact: true }).click()
await page.locator('#title').fill('Position fenêtre Palace')
await page.locator('#description').fill('Tenir depuis le coin')
await page.getByRole('button', { name: 'Publier' }).click()
await page.waitForURL(/\/\?map=|\/$/)
step('publication → retour liste : ' + page.url())

// 4. filtres
await page.goto(BASE)
await page.getByText('2 cartes').waitFor()
await page.getByRole('button', { name: /^Mirage\s*2$/ }).click()
await page.getByRole('button', { name: /^CT\s*2$/ }).first().click()
await page.getByRole('button', { name: /^Stuff\s*1$/ }).click()
await page.getByText('1 carte', { exact: true }).waitFor()
if (!/map=\d+&side=CT&cat=\d+/.test(page.url())) throw new Error('URL filtres : ' + page.url())
step('filtres ET/OU + compteurs + URL : ' + page.url())
await page.getByLabel('Recherche').fill('palace')
await page.waitForTimeout(400)
await shot(page, '03-browse')
await page.getByRole('button', { name: 'Réinitialiser les filtres' }).click()
await page.getByText('2 cartes').waitFor(); step('réinitialiser')
await page.getByLabel('Recherche').fill('fenetre')
await page.getByText('1 carte', { exact: true }).waitFor(); step('recherche sans accents')
await page.getByLabel('Recherche').fill('')

// 5. détail
await page.getByRole('link', { name: /Smoke Palace depuis CT/ }).click()
await page.getByRole('dialog').waitFor()
if (!/\/c\/\d+$/.test(page.url())) throw new Error('URL détail')
await page.getByRole('dialog').getByText('Chaise rouge').waitFor()
await page.getByRole('button', { name: /Historique/ }).click()
await page.getByText('Carte créée').waitFor(); step('vue détaillée en modale + historique')
await shot(page, '04-detail')
const cardUrl = page.url()

// 6. membre : signale « à revoir », ne peut pas modifier
page = await ctxFor(users.member)
await page.goto(cardUrl)
await page.getByRole('heading', { name: 'Smoke Palace depuis CT' }).waitFor()
if (await page.getByRole('link', { name: /Modifier/ }).count()) throw new Error('membre peut modifier la carte d’autrui')
await page.getByRole('button', { name: /Signaler/ }).click()
await page.getByPlaceholder(/la smoke ne passe plus/).fill('Ne passe plus depuis la MAJ')
await page.getByRole('button', { name: 'Signaler', exact: true }).click()
await page.getByText('Ne passe plus depuis la MAJ').waitFor(); step('URL partageable + membre signale « À revoir »')
await page.getByRole('button', { name: /Dupliquer/ }).click()
await page.locator('#title').waitFor()
if ((await page.locator('#title').inputValue()) !== 'Smoke Palace depuis CT (copie)') throw new Error('dupliquer')
step('dupliquer pré-remplit le formulaire')
await page.goto(BASE + '/?view=review')
await page.getByText('1 carte', { exact: true }).waitFor(); step('filtre « À revoir »')

// 7. admin : zones à valider, fusion
page = await ctxFor(users.admin)
await page.goto(BASE + '/admin/zones')
await page.getByText('Zones proposées à valider (1)').waitFor()
await shot(page, '05-admin-zones')
page.once('dialog', (d) => d.accept())
await page.getByLabel('Fusionner avec').selectOption({ label: 'Palace' })
await page.getByText('Zones fusionnées').waitFor(); step('fusion de zone (admin)')

// 8. import CSV
await page.goto(BASE + '/import')
await page.getByPlaceholder(/colle le contenu CSV/).fill('titre;liens;map;side;roles;categories;zones\nImport 1;https://imgur.com/AbC123x;mirage;ct;fixe a;position;Jungle\nImport 2;;Nuke;X;;Inconnue;')
await page.getByText('1 valide(s)').waitFor()
await page.getByText(/Side invalide/).waitFor()
await shot(page, '06-import')
await page.getByRole('button', { name: 'Importer 1 carte' }).click()
await page.getByText('1 carte importée.').waitFor(); step('import CSV avec prévisualisation')

// 9. mobile
page = await ctxFor(users.member, { width: 390, height: 844 })
await page.goto(BASE)
await page.getByLabel('Ajouter une carte').waitFor()
await shot(page, '07-mobile')
await page.getByRole('button', { name: /^Filtres/ }).click()
await shot(page, '08-mobile-filters')
await page.goto(BASE + '/new?map=5&side=CT')
await page.getByText('Pré-rempli avec les filtres actifs.').waitFor()
await shot(page, '09-mobile-form')
// sauvegarde locale : rechargement sans perte
await page.locator('#title').fill('Ne pas perdre ce titre')
await page.waitForTimeout(600)
await page.reload()
await page.getByText('Saisie non terminée restaurée.').waitFor()
if ((await page.locator('#title').inputValue()) !== 'Ne pas perdre ce titre') throw new Error('restauration')
step('saisie restaurée après rechargement')
await page.getByRole('button', { name: 'Repartir de zéro' }).click()
if ((await page.locator('#title').inputValue()) !== '') throw new Error('repartir de zéro')
// modification de sa propre carte (la carte importée n'est pas à lui, la copie non plus) : on édite en admin
page = await ctxFor(users.admin)
await page.goto(BASE + '/c/2/edit')
await page.locator('#title').fill('Position fenêtre Palace (maj)')
await page.getByRole('button', { name: 'Enregistrer' }).click()
await page.getByRole('heading', { name: 'Position fenêtre Palace (maj)' }).waitFor()
await page.getByRole('button', { name: /Historique/ }).click()
await page.getByText(/Titre : « Position fenêtre Palace » → « Position fenêtre Palace \(maj\) »/).waitFor()
await shot(page, '10-edit-history'); step('mobile : FAB, filtres repliables, formulaire')

// 10. cartes de démo + tableau de bord
page = await ctxFor(users.admin)
await page.goto(BASE + '/admin/demo')
await page.getByRole('button', { name: 'Charger les cartes de démo' }).click()
await page.getByText('13 cartes et 4 principes de démo créés').waitFor({ timeout: 60000 })
step('13 cartes + 4 principes de démo créés')
await page.goto(BASE + '/?view=drafts')
await page.getByText('[Démo] Brouillon de test').waitFor()
await page.goto(BASE + '/?view=review')
await page.getByText('[Démo] Flash pop Mid').waitFor(); step('démo : brouillon privé et carte « À revoir »')
await page.goto(BASE + '/')
await shot(page, '11-demo-grid')
await page.getByRole('link', { name: /Exé B complète/ }).click()
await page.getByRole('dialog').getByText('Ouvrir ↗').waitFor()
const before = page.url()
await page.keyboard.press('ArrowRight')
await page.waitForURL((u) => u.toString() !== before)
await page.getByRole('button', { name: /Carte précédente/ }).click()
await page.waitForURL(before); step('détail : navigation précédente / suivante')
await shot(page, '12-demo-detail')
await page.keyboard.press('Escape')
// rounds lancés : filtre, badge, formulaire conditionnel
await page.goto(BASE + '/')
await page.getByRole('button', { name: /^Rush\s*1$/ }).click()
await page.getByText('1 carte', { exact: true }).waitFor()
if (!/round=\d+/.test(page.url())) throw new Error('filtre round absent de l’URL')
await page.getByText('⚡ Rush').first().waitFor(); step('filtre « Round lancé » + badge')
await page.goto(BASE + '/new')
if (await page.getByText('Type de round').count()) throw new Error('type de round visible sans la catégorie')
await page.getByRole('button', { name: 'Round lancé', exact: true }).click()
await page.getByText(/\d+\. Type de round/).waitFor()
await page.getByRole('button', { name: 'Déclic', exact: true }).waitFor(); step('formulaire : type de round si « Round lancé »')

// principes de jeu
await page.goto(BASE + '/principes')
await page.getByText('[Démo] Toujours jouer en trade').waitFor()
await shot(page, '15-principles')
await page.getByText('[Démo] Toujours jouer en trade').click()
await page.getByRole('heading', { name: 'Cartes rattachées (2)' }).waitFor(); step('principes : liste par thème + cartes rattachées')
await shot(page, '16-principle-detail')
await page.getByRole('link', { name: /Rush B fumé/ }).first().click()
await page.getByRole('dialog').getByText('[Démo] Un rush se déclenche sur une info, pas sur un timer').waitFor()
await page.getByRole('dialog').getByText('via étiquettes').first().waitFor(); step('carte : principes rattachés + via étiquettes')
await shot(page, '17-card-principles')
await page.keyboard.press('Escape')
await page.goto(BASE + '/principes/new')
await page.locator('#ptitle').fill('Jouer les post-plants en crossfire')
await page.getByRole('button', { name: 'T', exact: true }).click()
await page.getByRole('button', { name: 'Post-plant', exact: true }).click()
await page.getByText(/→ 1 carte concernée/).waitFor()
await page.getByRole('button', { name: 'Créer le principe' }).click()
await page.getByRole('heading', { name: /Concernées par les étiquettes \(1\)/ }).waitFor(); step('création d’un principe par étiquettes')

await page.goto(BASE + '/stats')
await page.getByText('Couverture map × rôle').waitFor()
await page.getByText('Cartes dans la base').waitFor()
await shot(page, '13-dashboard')
await page.getByRole('radio', { name: 'T', exact: true }).click()
await page.locator('th', { hasText: 'Extre A' }).waitFor()
await page.getByRole('radio', { name: '12 mois' }).click()
await page.screenshot({ path: `${SHOTS}/14-dashboard-full.png`, fullPage: true })
step('tableau de bord : KPI, activité, couverture CT/T, périodes')
page.once('dialog', (d) => d.accept())
await page.goto(BASE + '/admin/demo')
await page.getByRole('button', { name: /Supprimer les données de démo/ }).click()
await page.getByText('Données de démo supprimées').waitFor(); step('suppression des données de démo')

// 11. équipes : l'admin crée une équipe, le capitaine invite une recrue
page = await ctxFor(users.admin)
await page.goto(BASE + '/equipes')
await page.getByLabel("Nom de l'équipe").fill('Alpha')
await page.getByLabel('Capitaine').selectOption({ label: 'Capitaine : Apex' })
await page.getByRole('button', { name: 'Créer' }).click()
await page.getByRole('heading', { name: 'Alpha' }).waitFor(); step('admin crée une équipe avec son capitaine')
page = await ctxFor(users.member)
await page.goto(BASE + '/equipes')
await page.getByText('Capitaine', { exact: true }).first().waitFor()
await page.getByLabel('Pseudo du joueur invité').fill('Recrue')
await page.getByRole('button', { name: 'Inviter' }).click()
const recrueLink = await page.getByLabel("Lien d'inscription").inputValue()
await page.keyboard.press('Escape')
await page.getByText('Invitations en attente').waitFor()
await shot(page, '18-teams')
const recrue = await ctxFor(null)
await signup(recrue, recrueLink, { email: 'recrue@team.gg', password: 'recrue-mdp-123' })
await recrue.getByRole('link', { name: 'Compétences' }).waitFor(); step('capitaine invite une recrue, qui s’inscrit par son lien et rejoint l’équipe')

// 12. compétences : objectif d'équipe propagé, la recrue progresse
await page.goto(BASE + '/competences?vue=matrice')
await page.getByRole('button', { name: /^Crosshair placement \(équipe\) : Non travaillé/ }).click()
page.once('dialog', (d) => d.accept())
await page.getByRole('menuitemradio', { name: 'À travailler' }).click()
await page.getByText(/passé « à travailler » chez 2 joueurs/).waitFor(); step('capitaine : objectif d’équipe propagé aux 2 joueurs')
await shot(page, '19-skills-matrix')
await page.getByRole('tab', { name: 'À travailler' }).click()
await page.locator('article', { hasText: 'Crosshair placement' }).getByText('2 à travailler').waitFor()
await shot(page, '20-skills-towork')
await recrue.goto(BASE + '/competences?vue=joueur')
const col = recrue.locator('section', { hasText: 'À travailler' }).first()
await col.getByText('Crosshair placement').waitFor()
await col.getByText('objectif d’équipe').first().waitFor()
if (await recrue.getByRole('button', { name: /\(équipe\)/ }).count()) throw new Error('joueur : statut d’équipe modifiable')
await col.getByRole('button', { name: /Crosshair placement · Recrue : À travailler/ }).click()
await recrue.getByRole('menuitemradio', { name: 'Acquis' }).click()
await recrue.locator('section', { hasText: 'Acquis' }).last().getByText('Crosshair placement').waitFor()
await recrue.reload()
await recrue.locator('section', { hasText: 'Acquis' }).last().getByText('Crosshair placement').waitFor()
step('fiche joueur : la recrue passe sa compétence « acquis »')
await shot(recrue, '21-skills-player')

// 13. lien d'inscription (admin) puis connexion email + mot de passe
page = await ctxFor(users.admin)
await page.goto(BASE + '/admin/membres')
await page.getByLabel('Pseudo').fill('Coach')
await page.getByRole('button', { name: 'Inviter' }).click()
const invite = await page.getByLabel("Lien d'inscription").inputValue()
await shot(page, '22-invite-link')
page = await ctxFor(null)
await signup(page, invite, { email: 'coach@team.gg', password: 'coach-mdp-123', shotName: '23-signup' })
await page.getByRole('link', { name: 'Compétences' }).waitFor(); step("lien d'inscription : compte créé (email + mot de passe)")
// Le lien ne sert qu'une fois.
await page.goto(invite)
await page.getByText('a déjà été utilisé').waitFor(); step("lien d'inscription : refusé à la 2e utilisation")
// Déconnexion puis connexion avec l'email et le mot de passe choisis.
await page.request.post(BASE + '/api/auth/logout', { headers: { 'x-requested-with': 'cs2kb' } })
await page.goto(BASE)
await page.getByLabel('Email', { exact: true }).fill('coach@team.gg')
await page.getByLabel('Mot de passe').fill('mauvais-mdp')
await page.getByRole('button', { name: 'Se connecter' }).click()
await page.getByText('Email ou mot de passe incorrect.').waitFor()
await page.getByLabel('Mot de passe').fill('coach-mdp-123')
await page.getByRole('button', { name: 'Se connecter' }).click()
await page.getByRole('link', { name: 'Compétences' }).waitFor(); step('connexion par email + mot de passe')

await browser.close()
if (errors.length) { console.log('ERREURS NAVIGATEUR:\n' + errors.join('\n')); process.exit(1) }
console.log('E2E OK')
